apiVersion: v1
kind: ConfigMap
metadata:
  name: loan-predictor-config
  namespace: default
data:
  MLFLOW_TRACKING_URI: "http://mlflow-service:5001"
  PROMETHEUS_PORT: "8000"
  LOG_LEVEL: "INFO"
  MODEL_VERSION: "1.0.0"